"""Adiciona campo is_rr a instrutores

Revision ID: <003e0ad4ae25>
Revises: 2986b6cc5303
Create Date: <sua_data_de_criacao_aqui>

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '<003e0ad4ae25>'
down_revision = '2986b6cc5303'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_rr', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_column('is_rr')

    # ### end Alembic commands ###