"""Adiciona nome_completo ao modelo Aluno

Revision ID: 0724fd5e62e3
Revises: e890e0e6b7b2
Create Date: 2025-09-03 18:50:59.704148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0724fd5e62e3'
down_revision = 'e890e0e6b7b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=120), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alunos', schema=None) as batch_op:
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###
