"""Adiciona configuracoes de visibilidade as semanas

Revision ID: 079e6ee259c9
Revises: 5fa5111a0301
Create Date: 2025-09-15 13:57:32.488906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079e6ee259c9'
down_revision = '5fa5111a0301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_periodos_extras', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mostrar_sabado', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('periodos_sabado', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mostrar_domingo', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('periodos_domingo', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.drop_column('periodos_domingo')
        batch_op.drop_column('mostrar_domingo')
        batch_op.drop_column('periodos_sabado')
        batch_op.drop_column('mostrar_sabado')
        batch_op.drop_column('mostrar_periodos_extras')

    # ### end Alembic commands ###
