"""Adiciona ciclo as semanas

Revision ID: 1cb7ad5daa43
Revises: 5d81221b9616
Create Date: 2025-09-15 15:34:34.038427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cb7ad5daa43'
down_revision = '5d81221b9616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.drop_column('ciclo')

    # ### end Alembic commands ###
