"""Adiciona nome de guerra e posto/graduacao

Revision ID: 2986b6cc5303
Revises: ced6e557a2f1
Create Date: 2025-09-11 18:43:24.509480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2986b6cc5303'
down_revision = 'ced6e557a2f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('posto_graduacao', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_de_guerra', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nome_de_guerra')

    with op.batch_alter_table('instrutores', schema=None) as batch_op:
        batch_op.drop_column('posto_graduacao')

    # ### end Alembic commands ###
