"""Adiciona campo nome_completo a User

Revision ID: 45548fc01ed5
Revises: b871d6901aa1
Create Date: 2025-09-05 12:30:40.452594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45548fc01ed5'
down_revision = 'b871d6901aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_completo', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nome_completo')

    # ### end Alembic commands ###
