"""Refatora visibilidade de periodos extras para controle individual

Revision ID: 5d81221b9616
Revises: 079e6ee259c9
Create Date: 2025-09-15 14:15:38.311655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d81221b9616'
down_revision = '079e6ee259c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_periodo_13', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mostrar_periodo_14', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('mostrar_periodo_15', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('mostrar_periodos_extras')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('semanas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mostrar_periodos_extras', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
        batch_op.drop_column('mostrar_periodo_15')
        batch_op.drop_column('mostrar_periodo_14')
        batch_op.drop_column('mostrar_periodo_13')

    # ### end Alembic commands ###
