"""Adiciona ciclos as disciplinas e atualiza existentes

Revision ID: 5fa5111a0301
Revises: <003e0ad4ae25>
Create Date: 2025-09-15 13:37:37.999628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fa5111a0301'
down_revision = '<003e0ad4ae25>'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ciclo', sa.Integer(), server_default='1', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_column('ciclo')

    # ### end Alembic commands ###
