"""Torna instrutor_id_1 opcional na tabela disciplina_turmas

Revision ID: 80279942b785
Revises: 5235bd830a0c
Create Date: 2025-09-09 11:20:44.694413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80279942b785'
down_revision = '5235bd830a0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina_turmas', schema=None) as batch_op:
        batch_op.alter_column('instrutor_id_1',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplina_turmas', schema=None) as batch_op:
        batch_op.alter_column('instrutor_id_1',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
