"""Configuracao inicial do banco de dados

Revision ID: 83de610663e8
Revises: 
Create Date: 2025-08-29 11:15:22.313537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83de610663e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_aluno', sa.String(length=20), nullable=True),
    sa.Column('matricula', sa.String(length=20), nullable=False),
    sa.Column('opm', sa.String(length=50), nullable=False),
    sa.Column('num_aluno', sa.String(length=20), nullable=True),
    sa.Column('pelotao', sa.String(length=20), nullable=False),
    sa.Column('funcao_atual', sa.String(length=50), nullable=True),
    sa.Column('foto_perfil', sa.String(length=255), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_aluno'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('instrutores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=14), nullable=False),
    sa.Column('especializacao', sa.String(length=100), nullable=False),
    sa.Column('formacao', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materia', sa.String(length=100), nullable=False),
    sa.Column('carga_horaria_prevista', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('instrutor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instrutor_id'], ['instrutores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('materia')
    )
    op.create_table('historico_alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_fim', sa.DateTime(), nullable=True),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('data_conclusao', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('disciplina_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('historico_disciplinas')
    op.drop_table('historico_alunos')
    op.drop_table('disciplinas')
    op.drop_table('instrutores')
    op.drop_table('alunos')
    op.drop_table('users')
    # ### end Alembic commands ###
