"""Adiciona vinculo de disciplina com escola

Revision ID: 96c4485d9f12
Revises: 33d722b47215
Create Date: 2025-09-18 14:41:30.437525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c4485d9f12'
down_revision = '33d722b47215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_disciplinas_schools_school_id', 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disciplinas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_disciplinas_schools_school_id', type_='foreignkey')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
