"""Adiciona colunas de notas p1, p2 e rec em historico_disciplina

Revision ID: 99fd34ed88fd
Revises: 80279942b785
Create Date: 2025-09-09 17:01:14.783821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99fd34ed88fd'
down_revision = '80279942b785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_disciplinas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nota_p1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nota_p2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('nota_rec', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historico_disciplinas', schema=None) as batch_op:
        batch_op.drop_column('nota_rec')
        batch_op.drop_column('nota_p2')
        batch_op.drop_column('nota_p1')

    # ### end Alembic commands ###
