"""Cria tabela turma_cargos

Revision ID: a1b2c3d4e5f6
Revises: 99fd34ed88fd
Create Date: 2025-09-10 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '99fd34ed88fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('turma_cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo_nome', sa.String(length=100), nullable=False),
    sa.Column('turma_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['turma_id'], ['turmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma_cargos')
    # ### end Alembic commands ###