"""Adiciona school_id a Turma

Revision ID: b8e7b8ba5285
Revises: b5831b06a6bc
Create Date: 2025-09-15 10:37:51.192991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8e7b8ba5285'
down_revision = 'b5831b06a6bc'
branch_labels = None
depends_on = None


def upgrade():
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_turmas')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_turmas_school_id_schools', 'schools', ['school_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turmas', schema=None) as batch_op:
        batch_op.drop_constraint('fk_turmas_school_id_schools', type_='foreignkey')
        batch_op.drop_column('school_id')

    # ### end Alembic commands ###
