"""Adiciona funcionalidade de questionário

Revision ID: bb03d68df6f1
Revises: 96c4485d9f12
Create Date: 2025-09-25 13:32:05.240855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb03d68df6f1'
down_revision = '96c4485d9f12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perguntas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=500), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('opcoes_respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=200), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respostas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('questionario_id', sa.Integer(), nullable=False),
    sa.Column('pergunta_id', sa.Integer(), nullable=False),
    sa.Column('opcao_resposta_id', sa.Integer(), nullable=True),
    sa.Column('texto_livre', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['opcao_resposta_id'], ['opcoes_respostas.id'], ),
    sa.ForeignKeyConstraint(['pergunta_id'], ['perguntas.id'], ),
    sa.ForeignKeyConstraint(['questionario_id'], ['questionarios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respostas')
    op.drop_table('opcoes_respostas')
    op.drop_table('perguntas')
    op.drop_table('questionarios')
    # ### end Alembic commands ###
